// Mock data for AI Career Navigator

export const mockUser = {
  id: "user-1",
  name: "김서현",
  email: "seohyun@example.com",
  school: "서울대학교",
  major: "컴퓨터공학과",
  grade: 3,
  targetJob: "백엔드 개발자",
  targetField: "IT/소프트웨어",
  profileImage: null,
  skills: ["Java", "Python", "Spring Boot", "React", "TypeScript", "MySQL", "Git", "Docker"],
  certifications: [
    { name: "정보처리기사", status: "취득완료", date: "2025-06" },
    { name: "SQLD", status: "준비중", date: null },
    { name: "AWS SAA", status: "미취득", date: null },
  ],
  projects: [
    {
      title: "온라인 쇼핑몰 플랫폼",
      description: "Spring Boot + React 기반의 풀스택 이커머스 플랫폼 개발",
      tech: ["Spring Boot", "React", "MySQL", "AWS"],
      period: "2025.03 - 2025.06",
    },
    {
      title: "AI 챗봇 서비스",
      description: "OpenAI API를 활용한 고객 상담 챗봇 시스템 구축",
      tech: ["Python", "FastAPI", "OpenAI", "Redis"],
      period: "2025.09 - 2025.12",
    },
    {
      title: "실시간 주식 분석 대시보드",
      description: "WebSocket 기반 실시간 주식 데이터 시각화 웹 애플리케이션",
      tech: ["Next.js", "TypeScript", "WebSocket", "Chart.js"],
      period: "2026.01 - 2026.03",
    },
  ],
  activities: [
    {
      title: "Google Developer Student Club",
      role: "멤버",
      period: "2025.03 - 2026.02",
      description: "웹 개발 스터디 참여 및 해커톤 출전",
    },
    {
      title: "오픈소스 컨트리뷰톤",
      role: "참가자",
      period: "2025.07 - 2025.09",
      description: "Apache Kafka 한글 문서화 기여",
    },
  ],
  awards: [
    { title: "교내 SW 경진대회", prize: "최우수상", year: "2025" },
  ],
};

export const mockAnalysis = {
  overallScore: 72,
  scores: {
    techSkills: 78,
    practicalExp: 70,
    certifications: 55,
    projectDiversity: 75,
    activities: 60,
    planning: 65,
  },
  strengths: [
    "프로젝트 경험 3건 보유, 실무 협업 및 Git 활용 능력 우수",
    "Spring Boot + React 기반 풀스택 개발 경험",
    "AI/ML 분야에 대한 실무 프로젝트 경험 보유",
    "Google DSC 등 개발 커뮤니티 활동 경험",
  ],
  weaknesses: [
    "목표 직무 관련 국가공인 자격증 부재 (SQLD 미취득)",
    "IT 분야 대외활동 경험이 상대적으로 부족",
    "클라우드 인프라(AWS/GCP) 실무 경험 제한적",
    "체계적인 학습 일정 관리 부족",
  ],
  missingSkills: ["Kubernetes", "CI/CD", "시스템 설계", "대규모 트래픽 처리", "모니터링"],
  recommendations: [
    "SQLD 자격증 취득 우선 추천",
    "AWS SAA 자격증 도전 권장",
    "오픈소스 기여 활동 확대",
    "시스템 설계 스터디 참여 추천",
  ],
};

export const mockRecommendations = {
  certifications: [
    {
      id: "cert-1",
      title: "SQLD (SQL 개발자)",
      category: "데이터베이스",
      priority: "높음",
      reason: "백엔드 개발자에게 필수적인 SQL 역량을 증명할 수 있는 자격증입니다. 현재 DB 관련 프로젝트 경험은 있으나 공인 자격증이 없어 보완이 필요합니다.",
      examDate: "2026-06-07",
      studyPeriod: "약 2개월",
      difficulty: "중급",
    },
    {
      id: "cert-2",
      title: "AWS Solutions Architect Associate",
      category: "클라우드",
      priority: "중간",
      reason: "클라우드 인프라 역량이 부족한 상태입니다. AWS SAA는 백엔드 개발자의 클라우드 역량을 증명하는 가장 기본적인 자격증입니다.",
      examDate: "수시",
      studyPeriod: "약 3개월",
      difficulty: "중급",
    },
    {
      id: "cert-3",
      title: "리눅스마스터 2급",
      category: "인프라",
      priority: "낮음",
      reason: "서버 운영 및 배포 환경에 대한 기본기를 다질 수 있습니다.",
      examDate: "2026-09-12",
      studyPeriod: "약 1개월",
      difficulty: "초급",
    },
  ],
  activities: [
    {
      id: "act-1",
      title: "네이버 부스트캠프 웹·모바일",
      category: "교육",
      status: "모집예정",
      period: "2026.07 - 2026.12",
      description: "네이버 커넥트재단에서 운영하는 실무형 개발자 양성 프로그램",
      skills: ["JavaScript", "Node.js", "React"],
      reason: "실무 프로젝트 경험 확대 및 네트워킹 기회 제공",
    },
    {
      id: "act-2",
      title: "SW마에스트로 17기",
      category: "정부지원",
      status: "모집중",
      period: "2026.06 - 2026.11",
      description: "과학기술정보통신부 주관 소프트웨어 인재 양성 프로그램",
      skills: ["팀 프로젝트", "멘토링", "창업"],
      reason: "체계적인 멘토링과 팀 프로젝트 경험 제공",
    },
    {
      id: "act-3",
      title: "카카오 테크 인턴십",
      category: "인턴십",
      status: "모집예정",
      period: "2026.07 - 2026.08",
      description: "카카오 서비스 개발 실무 인턴 프로그램",
      skills: ["Java", "Spring", "Kotlin"],
      reason: "목표 직무와 직접 관련된 실무 경험 확보 가능",
    },
  ],
  contests: [
    {
      id: "con-1",
      title: "공개 SW 개발자 대회",
      organizer: "과학기술정보통신부",
      status: "모집중",
      deadline: "2026-05-15",
      prize: "대상 1,000만원",
      field: "오픈소스",
      description: "오픈소스 소프트웨어 개발 역량을 겨루는 국내 최대 규모 대회",
      reason: "오픈소스 기여 경험을 확대하고 포트폴리오를 강화할 수 있습니다",
    },
    {
      id: "con-2",
      title: "TOPCIT 정기평가",
      organizer: "IITP",
      status: "모집중",
      deadline: "2026-05-20",
      prize: "성적 우수자 인센티브",
      field: "SW역량평가",
      description: "SW 역량을 종합적으로 평가하는 국가 공인 시험",
      reason: "객관적인 SW 역량 점수를 확보하여 이력서에 활용 가능합니다",
    },
  ],
};

export const mockRoadmap = {
  targetJob: "백엔드 개발자",
  stages: [
    {
      level: "초급",
      title: "기초 역량 확보",
      duration: "1-2개월",
      completed: true,
      items: [
        { title: "Java 기초 문법 및 OOP", completed: true, resource: "인프런 - 김영한 Java 기본" },
        { title: "Git & GitHub 활용", completed: true, resource: "생활코딩 Git" },
        { title: "SQL 기초", completed: true, resource: "프로그래머스 SQL 고득점 Kit" },
        { title: "Linux 기초 명령어", completed: false, resource: "리눅스마스터 교재" },
      ],
    },
    {
      level: "중급",
      title: "핵심 기술 심화",
      duration: "2-3개월",
      completed: false,
      items: [
        { title: "Spring Boot 핵심 원리", completed: true, resource: "인프런 - 김영한 Spring 핵심 원리" },
        { title: "JPA & 데이터 접근 기술", completed: true, resource: "인프런 - JPA 실전편" },
        { title: "REST API 설계", completed: false, resource: "RESTful API 디자인 가이드" },
        { title: "DB 설계 및 최적화", completed: false, resource: "Real MySQL 8.0" },
        { title: "SQLD 자격증 취득", completed: false, resource: "SQLD 교재 + 기출문제" },
      ],
    },
    {
      level: "심화",
      title: "실무 역량 완성",
      duration: "3-4개월",
      completed: false,
      items: [
        { title: "Docker & 컨테이너 기술", completed: false, resource: "Docker 공식 문서" },
        { title: "CI/CD 파이프라인 구축", completed: false, resource: "GitHub Actions 튜토리얼" },
        { title: "AWS 클라우드 배포", completed: false, resource: "AWS SAA 준비" },
        { title: "시스템 설계 기초", completed: false, resource: "가상 면접 사례로 배우는 대규모 시스템 설계" },
        { title: "포트폴리오 프로젝트 완성", completed: false, resource: "개인 프로젝트" },
      ],
    },
  ],
};

export const mockInternshipGuide = {
  targetJob: "백엔드 개발자",
  requiredSkills: [
    { name: "Java/Kotlin", level: "필수", userLevel: 80 },
    { name: "Spring Boot", level: "필수", userLevel: 70 },
    { name: "RDBMS (MySQL/PostgreSQL)", level: "필수", userLevel: 65 },
    { name: "Git", level: "필수", userLevel: 85 },
    { name: "REST API", level: "필수", userLevel: 70 },
    { name: "Docker", level: "우대", userLevel: 40 },
    { name: "AWS/GCP", level: "우대", userLevel: 30 },
    { name: "Redis/Kafka", level: "우대", userLevel: 35 },
  ],
  resumeTips: [
    "프로젝트에서 본인이 맡은 역할과 기여도를 구체적으로 작성하세요",
    "기술적 성과를 수치로 표현하세요 (예: 응답 속도 30% 개선)",
    "GitHub 링크와 배포 URL을 반드시 포함하세요",
    "사용한 기술 스택과 선택 이유를 명확히 기술하세요",
  ],
  interviewChecklist: [
    { category: "CS 기초", items: ["자료구조 (배열, 해시, 트리, 그래프)", "알고리즘 (정렬, 탐색, DP)", "네트워크 (HTTP, TCP/IP, REST)", "운영체제 (프로세스, 스레드, 메모리)"] },
    { category: "백엔드", items: ["Spring IoC/DI 원리", "JPA N+1 문제 해결", "트랜잭션 관리", "API 설계 원칙"] },
    { category: "DB", items: ["인덱스 동작 원리", "정규화/반정규화", "SQL 쿼리 최적화", "트랜잭션 격리 수준"] },
  ],
};

export const mockCalendarEvents = [
  { id: "ev-1", title: "SQLD 공부", date: "2026-04-08", type: "study", ai: true },
  { id: "ev-2", title: "SQLD 공부", date: "2026-04-10", type: "study", ai: true },
  { id: "ev-3", title: "SQLD 공부", date: "2026-04-12", type: "study", ai: true },
  { id: "ev-4", title: "공개 SW 대회 마감", date: "2026-05-15", type: "deadline", ai: false },
  { id: "ev-5", title: "TOPCIT 마감", date: "2026-05-20", type: "deadline", ai: false },
  { id: "ev-6", title: "SQLD 시험", date: "2026-06-07", type: "exam", ai: false },
  { id: "ev-7", title: "Spring Boot 프로젝트 코드리뷰", date: "2026-04-09", type: "personal", ai: false },
  { id: "ev-8", title: "SW마에스트로 지원서 작성", date: "2026-04-14", type: "personal", ai: true },
  { id: "ev-9", title: "REST API 설계 학습", date: "2026-04-11", type: "study", ai: true },
  { id: "ev-10", title: "Docker 기초 학습", date: "2026-04-15", type: "study", ai: true },
];

export const mockTeamPosts = [
  {
    id: "team-1",
    author: "이준호",
    school: "연세대학교",
    major: "소프트웨어학과",
    targetJob: "풀스택 개발자",
    title: "공개 SW 개발자 대회 팀원 모집",
    description: "오픈소스 프로젝트로 공개 SW 대회에 참가할 팀원을 모집합니다. 백엔드 1명, 프론트엔드 1명 모집 중입니다.",
    skills: ["React", "Node.js", "PostgreSQL"],
    currentMembers: 2,
    maxMembers: 4,
    status: "모집중",
    createdAt: "2026-04-05",
  },
  {
    id: "team-2",
    author: "박지영",
    school: "고려대학교",
    major: "컴퓨터학과",
    targetJob: "데이터 엔지니어",
    title: "SQLD 스터디 모집 (6월 시험 목표)",
    description: "SQLD 6월 시험을 목표로 같이 공부할 스터디원을 모집합니다. 주 2회 온라인 스터디 예정입니다.",
    skills: ["SQL", "데이터베이스"],
    currentMembers: 3,
    maxMembers: 6,
    status: "모집중",
    createdAt: "2026-04-03",
  },
  {
    id: "team-3",
    author: "최민수",
    school: "카이스트",
    major: "전산학부",
    targetJob: "백엔드 개발자",
    title: "Spring Boot 사이드 프로젝트 팀원 모집",
    description: "Spring Boot + React로 커뮤니티 서비스를 만들 팀원을 구합니다. 매주 토요일 오프라인 미팅 예정입니다.",
    skills: ["Spring Boot", "React", "MySQL", "Docker"],
    currentMembers: 1,
    maxMembers: 3,
    status: "모집중",
    createdAt: "2026-04-06",
  },
  {
    id: "team-4",
    author: "정하은",
    school: "성균관대학교",
    major: "소프트웨어학과",
    targetJob: "프론트엔드 개발자",
    title: "SW마에스트로 17기 같이 지원할 분",
    description: "SW마에스트로에 같이 지원하고 준비할 팀원을 모집합니다. 지원서 피드백 및 면접 준비를 함께 하려 합니다.",
    skills: ["팀 프로젝트", "포트폴리오"],
    currentMembers: 2,
    maxMembers: 3,
    status: "모집중",
    createdAt: "2026-04-07",
  },
];

export const mockSuccessStories = [
  {
    name: "김OO",
    company: "네이버",
    position: "백엔드 개발자",
    quote: "AI Career Navigator 덕분에 부족한 부분을 정확히 파악하고 체계적으로 준비할 수 있었어요.",
    improvement: "역량 점수 58점 → 89점",
  },
  {
    name: "이OO",
    company: "카카오",
    position: "프론트엔드 개발자",
    quote: "맞춤형 학습 로드맵이 정말 큰 도움이 되었습니다. 방향을 잡고 집중할 수 있었어요.",
    improvement: "역량 점수 45점 → 82점",
  },
  {
    name: "박OO",
    company: "라인",
    position: "서버 개발자",
    quote: "공모전과 자격증 추천이 정확했어요. 추천받은 대회에서 수상까지 할 수 있었습니다.",
    improvement: "역량 점수 62점 → 91점",
  },
];
